import java.io.IOException;
import java.net.URL;
import java.net.URLConnection;
import java.util.List;
import java.util.Map;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author nitipatpipatprathung
 */
public class NetproAssign2 extends javax.swing.JFrame {

    /**
     * Creates new form NetproAssign2
     */
    public NetproAssign2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        URL1 = new javax.swing.JTextField();
        URL2 = new javax.swing.JTextField();
        GetPage = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        showURL2 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        showURL1 = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        Header = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        Thread = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nitipat Pipatprathung s5050348@kmitl.ac.th - Java Web Browser (Network Programming Class Assignment)");

        GetPage.setText("GO!");
        GetPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetPageActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(showURL2);

        jScrollPane2.setViewportView(showURL1);

        jScrollPane3.setViewportView(Header);

        jScrollPane4.setViewportView(Thread);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(URL2, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
                            .addComponent(URL1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GetPage)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(URL1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(URL2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(GetPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GetPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetPageActionPerformed
        // TODO add your handling code here:
           MyThread link1 = new MyThread(URL1.getText(), "Thread1");
        MyThread link2 = new MyThread(URL2.getText(), "Thread2");
        link1.start();
        link2.start();
    }//GEN-LAST:event_GetPageActionPerformed
/*
    public void Url1() {
        try {
            Thread.setText(Thread.getText() + "Thead1 : Start Get URL\n");
            showURL1.setPage(URL1.getText());
            Thread.setText(Thread.getText() + "Thead1 : GetPage\n");

            Thread.setText(Thread.getText() + "Thread1 : Print Header\n");

            ShowHeader(URL1.getText(), "Thread1 :");
            Thread.setText(Thread.getText() + "Thead1 : Finish\n");
        } catch (IOException ex) {
            //Logger.getLogger(Assign2.class.getName()).log(Level.SEVERE, null, ex);
            printf("not have URL1");
        }
    }                                       

    private void URL1ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
    }                            
*/
    public void ShowHeader(String URL, String Thread) {
        String url = URL;
        String thread = Thread;
        try {

            URL obj = new URL(url);
            URLConnection conn = obj.openConnection();
            Map<String, List<String>> map = conn.getHeaderFields();
            Header.setText(Header.getText() + thread + " :\n");

            for (Map.Entry<String, List<String>> entry : map.entrySet()) {
                Header.setText(Header.getText() + "Key : " + entry.getKey() + " ,Value : " + entry.getValue() + "\n");
            }
            Header.setText(Header.getText() + "\nGet HTTP Header For : " + thread + "\n");
            String server = conn.getHeaderField("Server");

            if (server == null) {
                Header.setText(Header.getText() + "'Server' is not found!\n");
            } else {
                Header.setText(Header.getText() + "Server : " + server + "\n");
            }
            Header.setText(Header.getText() + "Done\n________________________\n");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public class MyThread extends Thread {

        String link, thrNo;
        int delay = 5000;

        public MyThread(String url, String no) {
            link = url;
            thrNo = no;
        }

        @Override
        public void run() {

            try {
                Thread.setText(Thread.getText() + thrNo + " : Start Get URL\n");

                if (thrNo.equals("Thread1")) {
                    showURL1.setPage(link);

                }
                if (thrNo.equals("Thread2")) {
                    showURL2.setPage(link);

                }

                Thread.setText(Thread.getText() + thrNo + " : GetPage\n");

                Thread.setText(Thread.getText() + thrNo + " : Print Header\n");

                ShowHeader(link, thrNo);

                Thread.setText(Thread.getText() + thrNo + " : Finish\n");
            } catch (IOException ex) {
                //Logger.getLogger(Assign2.class.getName()).log(Level.SEVERE, null, ex);
                printf("cannot show");
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NetproAssign2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NetproAssign2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NetproAssign2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NetproAssign2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NetproAssign2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GetPage;
    private javax.swing.JTextPane Header;
    private javax.swing.JTextPane Thread;
    private javax.swing.JTextField URL1;
    private javax.swing.JTextField URL2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextPane showURL1;
    private javax.swing.JTextPane showURL2;
    // End of variables declaration//GEN-END:variables
    private void printf(String string) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}

